name:                tsg
version:             0.1.0.0
github:              "tsarn/tsg"
license:             MIT
author:              "Nikita Tsarev"
maintainer:          "nikts53@gmail.com"
copyright:           "2021 Nikita Tsarev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tsg#readme>

dependencies:
- base >= 4.7 && < 5
- raw-strings-qq >= 1.1
- mtl
- s-cargot >= 0.1.4.0
- text
- parsec
- containers

library:
  source-dirs: src

executables:
  tsg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tsg

tests:
  tsg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tsg
